# Generated by Django 4.2.30 on 2026-09-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("track", models.CharField(blank=True, max_length=160)),
                ("total_laps", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RaceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=120)),
                ("car", models.CharField(blank=True, max_length=120)),
                ("grid_position", models.PositiveIntegerField(default=1)),
                ("position", models.PositiveIntegerField(default=1)),
                ("current_lap", models.PositiveIntegerField(default=0)),
                ("lap_time", models.FloatField(blank=True, null=True)),
                ("total_time", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("racing", "Racing"),
                            ("finished", "Finished"),
                            ("dnf", "DNF"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("telemetry", models.JSONField(blank=True, default=dict)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="races.race",
                    ),
                ),
                (
                    "rig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="race_entries",
                        to="devices.rig",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "grid_position"],
            },
        ),
        migrations.AddConstraint(
            model_name="raceentry",
            constraint=models.UniqueConstraint(
                fields=("race", "rig"), name="unique_rig_per_race"
            ),
        ),
    ]
