# Generated by Django 4.2.30 on 2026-09-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_racer_rig_current_game_rig_display_name_and_more"),
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="simulator",
            field=models.CharField(blank=True, default="F1 25", max_length=80),
        ),
        migrations.AddField(
            model_name="raceentry",
            name="racer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="race_entries",
                to="devices.racer",
            ),
        ),
        migrations.AlterField(
            model_name="raceentry",
            name="driver_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
