# Generated by Django 4.2.30 on 2026-09-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("telemetry_port", models.PositiveIntegerField(default=20777)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("online", "Online"),
                            ("racing", "Racing"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="mock", max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("rig", "Rig"),
                            ("display", "Display"),
                            ("controller", "Controller"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="unknown", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "rig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="devices.rig",
                    ),
                ),
            ],
            options={
                "ordering": ["rig__name", "name"],
            },
        ),
    ]
