# Generated by Django 4.2.30 on 2026-09-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Racer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="rig",
            name="current_game",
            field=models.CharField(
                default="F1 25",
                help_text="Current simulator/runtime title for this rig.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="rig",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Operator-facing name shown on the control surface.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="rig",
            name="game_detection_mode",
            field=models.CharField(
                choices=[("manual", "Development / Manual"), ("auto", "Automatic")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rig",
            name="hostname",
            field=models.CharField(
                blank=True,
                help_text="Machine/technical identity for the rig.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="rig",
            name="assigned_racer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_rigs",
                to="devices.racer",
            ),
        ),
    ]
